//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace TestGrainInterface
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class TestGrainInterfaceFactory
    {
        

                        public static ITestGrainInterface GetGrain(long primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(ITestGrainInterface), 1092872112, primaryKey));
                        }

                        public static ITestGrainInterface GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(ITestGrainInterface), 1092872112, primaryKey, grainClassNamePrefix));
                        }

                        public static ITestGrainInterface GetGrain(Guid primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(ITestGrainInterface), 1092872112, primaryKey));
                        }

                        public static ITestGrainInterface GetGrain(Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(ITestGrainInterface), 1092872112, primaryKey, grainClassNamePrefix));
                        }

            public static ITestGrainInterface Cast(IAddressable grainRef)
            {
                
                return TestGrainInterfaceReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [Orleans.GrainReferenceAttribute("TestGrainInterface.ITestGrainInterface")]
        internal class TestGrainInterfaceReference : Orleans.GrainReference, ITestGrainInterface, Orleans.IAddressable
        {
            

            public static ITestGrainInterface Cast(IAddressable grainRef)
            {
                
                return (ITestGrainInterface) GrainReference.CastInternal(typeof(ITestGrainInterface), (GrainReference gr) => { return new TestGrainInterfaceReference(gr);}, grainRef, 1092872112);
            }

                protected override int InterfaceId { get { return 1092872112; } }

                public override bool IsCompatible(int interfaceId) { return interfaceId == this.InterfaceId; }

                protected override string InterfaceName { get { return "TestGrainInterface.ITestGrainInterface"; } }

                protected override string GetMethodName(int interfaceId, int methodId) { return TestGrainInterfaceMethodInvoker.GetMethodName(interfaceId, methodId); }
            
            protected internal TestGrainInterfaceReference(GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal TestGrainInterfaceReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            [Orleans.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                TestGrainInterfaceReference input = ((TestGrainInterfaceReference)(original));
                return ((TestGrainInterfaceReference)(GrainReference.CopyGrainReference(input)));
            }
            
            [Orleans.SerializerMethodAttribute()]
            public static void _Serializer(object original, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                TestGrainInterfaceReference input = ((TestGrainInterfaceReference)(original));
                GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [Orleans.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return TestGrainInterfaceReference.Cast(((Orleans.GrainReference)(GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public System.Threading.Tasks.Task<string> SayHelloAsync(string name)
            {

                return base.InvokeMethodAsync<System.String>(1363881158, new object[] {name}, TimeSpan.Zero );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [Orleans.MethodInvokerAttribute("TestGrainInterface.ITestGrainInterface", 1092872112)]
    internal class TestGrainInterfaceMethodInvoker : IGrainMethodInvoker
    {
        
        public int InterfaceId
        {
            get
            {
                return 1092872112;
            }
        }
        
        public async System.Threading.Tasks.Task<Object> Invoke(IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {
                if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1092872112:  // ITestGrainInterface
                        switch (methodId)
                        {
                            case 1363881158: 
                                return await ((ITestGrainInterface)grain).SayHelloAsync((String)arguments[0]);
                            default: 
                                throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1092872112:  // ITestGrainInterface
                    switch (methodId)
                    {
                        case 1363881158:
                            return "SayHelloAsync";
                    case -606142484:
                            return "GetProperties";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [Serializable()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class TestGrainInterfaceProperties
    {
        

            public Dictionary<string,object> AsDictionary()
            {  
                var retValue = new Dictionary<string,object>();
                return retValue;
            }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
