//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 414
#pragma warning disable 649
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace ClusterProtocol.Interfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ClusterRepFactory
    {
        

                        public static ClusterProtocol.Interfaces.IClusterRep GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(ClusterProtocol.Interfaces.IClusterRep), 1264905006, primaryKey));
                        }

                        public static ClusterProtocol.Interfaces.IClusterRep GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(ClusterProtocol.Interfaces.IClusterRep), 1264905006, primaryKey, grainClassNamePrefix));
                        }

            public static ClusterProtocol.Interfaces.IClusterRep Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ClusterRepReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("ClusterProtocol.Interfaces.ClusterProtocol.Interfaces.IClusterRep")]
        internal class ClusterRepReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, ClusterProtocol.Interfaces.IClusterRep
        {
            

            public static ClusterProtocol.Interfaces.IClusterRep Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (ClusterProtocol.Interfaces.IClusterRep) global::Orleans.Runtime.GrainReference.CastInternal(typeof(ClusterProtocol.Interfaces.IClusterRep), (global::Orleans.Runtime.GrainReference gr) => { return new ClusterRepReference(gr);}, grainRef, 1264905006);
            }
            
            protected internal ClusterRepReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ClusterRepReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1264905006;
                }
            }
            
            public override string InterfaceName
            {
                get
                {
                    return "ClusterProtocol.Interfaces.ClusterProtocol.Interfaces.IClusterRep";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ClusterRepReference input = ((ClusterRepReference)(original));
                return ((ClusterRepReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ClusterRepReference input = ((ClusterRepReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ClusterRepReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == 1928988877));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ClusterRepMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<string> ClusterProtocol.Interfaces.IClusterRep.GetInfo()
            {

                return base.InvokeMethodAsync<System.String>(-1168913303, null );
            }
            
            System.Threading.Tasks.Task ClusterProtocol.Interfaces.IClusterRep.PostInfo(string @info)
            {

                return base.InvokeMethodAsync<object>(-126448525, new object[] {@info} );
            }
            
            System.Threading.Tasks.Task ClusterProtocol.Interfaces.IClusterRep.Init(string @info)
            {

                return base.InvokeMethodAsync<object>(-151816209, new object[] {@info} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("ClusterProtocol.Interfaces.ClusterProtocol.Interfaces.IClusterRep", 1264905006)]
    internal class ClusterRepMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1264905006;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1264905006:  // IClusterRep
                        switch (methodId)
                        {
                            case -1168913303: 
                                return ((IClusterRep)grain).GetInfo().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -126448525: 
                                return ((IClusterRep)grain).PostInfo((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -151816209: 
                                return ((IClusterRep)grain).Init((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case 1928988877:  // IGrainWithIntegerKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1264905006:  // IClusterRep
                    switch (methodId)
                    {
                        case -1168913303:
                            return "GetInfo";
                    case -126448525:
                            return "PostInfo";
                    case -151816209:
                            return "Init";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case 1928988877:  // IGrainWithIntegerKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 649
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
